name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  SHA7: ${GITHUB_SHA::7}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}     
          tags: |
              type=sha,format=short,prefix=
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $SHA7
          labels: ${{ steps.meta.outputs.labels }}   

      - name: Step
        run: echo $SHA7
      - 
        name: Check out helm repo 
        uses: actions/checkout@v3
        with:
          repository: dearteno/mtlchart
          token: "${{ secrets.PAT }}"   
      -
       name: update helm
       uses: mikefarah/yq@master
       with:
        cmd: yq -i '.image.tag = "$SHA7"' 'stable/values.yaml'    

      - name: Commit and push changes
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

          git commit -am "update image tag $SHA7"
          git push        


