name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}     
          tags: |
              type=sha,format=short,prefix=
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}     
      - 
        name: Check out helm repo #uses: mikefarah/yq@master
        uses: actions/checkout@v3
        with:
          repository: dearteno/mtlchart
          token: "${{ secrets.PAT }}"   
      - name: ls
        run: echo ${ GITHUB_SHA:0:7 }
      -
       name: update helm
       uses: mikefarah/yq@master
       with:
        cmd: yq -i '.image.tag = "${ GITHUB_SHA:0:7 }"' 'stable/values.yaml'    

      - name: Commit and push changes
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"

          git commit -am "update image tag ${{ steps.meta.outputs.tags }}"
          git push        


